import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ParticlesModel from "./components/3dModels/ParticlesModel"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Felipe Albuquerque",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon " href="/icon.ico" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <ParticlesModel/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
